const AppActionsConstants = {
    UPDATE_TAG: 'UPDATE_TAG',
    LOAD_TAGS: 'LOAD_TAGS',
    LOAD_TAGS_SUCCESS: 'LOAD_TAGS_SUCCESS',
    LOAD_TAGS_FAILURE: 'LOAD_TAGS_FAILURE',
    SEARCH_RESTAURANT: 'SEARCH_RESTAURANT',
    SEARCH_RESTAURANT_SUCCESS: 'SEARCH_RESTAURANT_SUCCESS',
    SEARCH_RESTAURANT_FAILURE: 'SEARCH_RESTAURANT_FAILURE'
};

export { AppActionsConstants}
