const Search_UsersActionsConstants = {
    UPDATE_SEARCH_TYPE_USER: 'UPDATE_SEARCH_TYPE_USER',
    UPDATE_TAG_USER: 'UPDATE_TAG_USER',
    SEARCH_USERS: 'SEARCH_USERS',
    SEARCH_USERS_LOCATION: 'SEARCH_USERS_LOCATION',
    LOAD_USER: 'LOAD_USER',
    LOAD_USER_LOCATION: 'LOAD_USER_LOCATION',
    GLOBAL_FILTER_SEARCH: 'GLOBAL_FILTER_SEARCH'
    // LOAD_TAGS_FAILURE: 'LOAD_TAGS_FAILURE',
    // SEARCH_RESTAURANT_SUCCESS: 'SEARCH_RESTAURANT_SUCCESS',
    // SEARCH_RESTAURANT_FAILURE: 'SEARCH_RESTAURANT_FAILURE'
};

export { Search_UsersActionsConstants}
