const Search_RestsActionsConstants = {
    UPDATE_SEARCH_TYPE: 'UPDATE_SEARCH_TYPE',
    UPDATE_ADVANCED_SEARCH_TYPE: 'UPDATE_ADVANCED_SEARCH_TYPE',
    UPDATE_TAG_RESTATURANT: 'UPDATE_TAG_RESTATURANT',
    UPDATE_LOCATION_RESTATURANT: 'UPDATE_LOCATION_RESTATURANT',
    SEARCH_RESTAURANT: 'SEARCH_RESTAURANT',
    SEARCH_RESTAURANT_LOCATION: 'SEARCH_RESTAURANT_LOCATION',
    FILTER_RESTAURANT: 'FILTER_RESTAURANT',
    SEARCH_RESTAURANT_SUCCESS: 'SEARCH_RESTAURANT_SUCCESS',
    SEARCH_RESTAURANT_LOCATION_SUCCESS: 'SEARCH_RESTAURANT_LOCATION_SUCCESS',
    SEARCH_RESTAURANT_FAILURE: 'SEARCH_RESTAURANT_FAILURE',
    SEARCH_RESTAURANT_LOCATION_FAILURE: 'SEARCH_RESTAURANT_LOCATION_FAILURE',
    GLOBAL_FILTER_SEARCH_RESTS: 'GLOBAL_FILTER_SEARCH_RESTS',
    UPDATE_AVERAGE: 'UPDATE_AVERAGE',
    UPDATE_RESTAURANT_REVIEWS: 'UPDATE_RESTAURANT_REVIEWS',
    UPDATE_AVERAGE_ARR: 'UPDATE_AVERAGE_ARR',
    ADD_REVIEW: 'ADD_REVIEW',
    BATHROOM_QUALITY_TMP: 'BATHROOM_QUALITY_TMP',
    STAFF_KINDNESS_TMP: 'STAFF_KINDNESS_TMP',
    CLEANLINESS_TMP: 'CLEANLINESS_TMP',
    DRIVE_THRU_TMP: 'DRIVE_THRU_TMP',
    DELIVERY_SPEED_TMP: 'DELIVERY_SPEED_TMP',
    FOOD_QUALITY_TMP: 'FOOD_QUALITY_TMP',
    UPLOAD_IMAGES: 'UPLOAD_IMAGES',
    UPDATE_IMAGES: 'UPDATE_IMAGES',
    UPDATE_TIME: 'UPDATE_TIME'
};

export { Search_RestsActionsConstants}
